-- Archivo: definitions/viajes_largos.sqlx

-- Configuración para crear una nueva tabla
config {
  type: "table"
}

-- El SELECT statement que define el contenido de nuestra tabla
SELECT
  id_campania, nombre_campania, tipo_canal, fecha_inicio, fecha_fin, costo_campania
FROM
  -- La función ref() es la clave de Dataform.
  -- Le dice que este modelo depende de la fuente 'bikeshare_trips' que declaramos antes.
  ${ref("campanias_marketing")}
WHERE
  tipo_canal = "Email"